import './globals.css'
import Link from 'next/link'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'

const sans = Open_Sans({ subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={sans.className}>
      <body className={sans.className}>
        <header className='flex justify-between items-center p-8'>
            <h1 className='font-bold text-lg'>H-Blog</h1>
            <nav>
              <Link href="/products" className='px-8'>Home</Link>
              <Link href="/about" className='px-8'>About</Link>
              <Link href="/posts" className='px-8'>Posts</Link>
              <Link href="/contact" className='px-8'>Contact</Link>
            </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
